libigl/libigl

python/CMakeLists.txt

Switched from manual addition of libraries to cmake find_package. Works on Ubuntu 15.10

Fixed OpenGL/GLFW related linking problems

---

python/README.md

First time using cmake - am I doing this the right way?

python build instructions.

---

include/igl/copyleft/cgal/assign_scalar.cpp
include/igl/copyleft/cgal/assign_scalar.h

Add ``float`` support in ``igl::copyleft::cgal::assign_scalar``

Support float in assign_scalar

---

tutorial/tutorial.md

The sum of those two matrices would be L_{flat} + A, however, we want Q = L_flat - 2A , or the negative of that if we want positive-definite.

fix typo in tutorial 502 and content error

---

include/igl/loop.cpp
include/igl/loop.h

This is a modified version of the igl::upsample code that performs loop subdivision instead of simply upsampling. The coefficients and rules are taken directly from https://graphics.stanford.edu/~mdfisher/subdivision.html.

Added loop subdivision functionality.

---

python/modules/copyleft/py_igl_cgal.cpp
python/py_doc.cpp
python/py_doc.h
python/py_igl/copyleft/cgal/py_RemeshSelfIntersectionsParam.cpp
python/py_igl/copyleft/cgal/py_remesh_self_intersections.cpp
python/python_shared.cpp

Added bindings for remesh_self_intersections and RemeshSelfIntersectionsParam.

Python: remesh_self_intersections

---

include/igl/flip_avoiding_line_search.cpp

a temporary fix for the bug. This should be able done in a better way.

fixed bugs in flip_avoiding_line_search.cpp

---

include/igl/HalfEdgeIterator.cpp
include/igl/HalfEdgeIterator.h

First commit fix two minor bugs in HalfEdgeIterator.
Second commit Separates .h/.cpp and added some documentation.
Third commit add additional explicit template instantiation to pass the build test locally.

Fix for HalfEdgeIterator

---

include/igl/readOFF.cpp

fix blank line error while opening OFF file

---

include/igl/embree/EmbreeIntersector.h
include/igl/viewer/Viewer.cpp
include/igl/viewer/Viewer.h

Fix some warnings emitted when user code is compiled with -Wall.

Fix some compilation warnings in viewer/EmbreeIntersector

---

include/igl/viewer/ViewerCore.cpp

See https://github.com/libigl/libigl/issues/524

Use igl::PI instead of M_PI to fix VS math error

---

python/py_doc.cpp
python/py_doc.h
python/py_igl.cpp
python/py_igl/py_writePLY.cpp
python/python_shared.cpp

Hopefully this should be a simple one - Added python binding for the writePLY function.

add python binding for writePLY

---

python/py_doc.cpp
python/py_doc.h
python/py_igl.cpp
python/py_igl/py_readPLY.cpp
python/python_shared.cpp

add wrapper for readPLY

---

include/igl/angle_bound_frame_fields.cpp

Somehow this line was not compiling properly with the latest version of Eigen ...

Compatibility with Eigen 3.3.4

---

include/igl/viewer/Viewer.cpp

Fix for bug described [here](https://github.com/libigl/libigl/commit/656175d56dcf7a7383769a9f495d1575fcd3a463#commitcomment-25351557)

ngui refresh fix

---

include/igl/AABB.cpp
include/igl/hessian.cpp
include/igl/hessian_energy.cpp

The change to file `AABB.cpp` is basically the same as #611, but doesn't update the submodules to whatever (see also #604).

Compatibility with Eigen 3.3

---

include/igl/opengl/glfw/imgui/ImGuiMenu.cpp

Minor touch-up to the ImGui menu.

ImGui menu: reduce spacing + remove label window frame.

---

include/igl/readSTL.h

Fix documentation of readSTL

---

include/igl/shapeup.cpp
include/igl/sparse_cached.cpp
include/igl/vertex_triangle_adjacency.cpp

Fixed some errors that appear when using Eigen3.3.
Still compatible with Eigen 3.2

Eigen3.3 compatibility

---

tests/include/igl/copyleft/cgal/order_facets_around_edges.cpp

Remove a cgal unit test temporarily.

---

include/igl/cylinder_with_caps.cpp
include/igl/cylinder_with_caps.h

cylinder with caps

---

include/igl/opengl/ViewerCore.cpp
include/igl/opengl/ViewerCore.h

Fix include

---

include/igl/copyleft/opengl2/render_to_tga.cpp
include/igl/copyleft/opengl2/tga.cpp
include/igl/principal_curvature.cpp
include/igl/readDMAT.cpp
include/igl/readMSH.cpp
include/igl/xml/serialize_xml.cpp

This pull request fixes several memory leaks.

Memory leak fixes

---

python/py_doc.cpp
python/py_doc.h
python/py_igl.cpp
python/py_igl/py_heat_geodesics.cpp

added the heat_geodesics python binding. tested it in my own project.

exposed heat_geodesics in python binding

---

tutorial/407_BiharmonicCoordinates/main.cpp
tutorial/604_Triangle/main.cpp

Added more comments so the methods used inside are explained in detail now

Added more comments to 407 and 604

---

include/igl/opengl/glfw/imgui/ImGuiTraits.h

fix compiler (Visual Studio 2015 error C2131) issue #1226 as discussed with @jdumas

fix compiler (VS 2015 error C2131) issue #1226

---

.travis.yml
cmake/libigl-cgal.yml

Now you can simply do (on Windows):
```
conda env create -f cmake/libigl-cgal.yml
conda activate libigl-cgal
cmake-gui
```
I can update instructions on the website once this is merged.

Add conda environment file for boost (helpful for Windows users).

---

include/igl/deprecated.h

See also: https://stackoverflow.com/a/21265197

update IGL_DEPRECATED to handle clang (e.g. on macOS) as well.

---

include/igl/dijkstra.h

Revise the documentation for dijkstra (fixes #1298)

---

include/igl/opengl/glfw/Viewer.cpp

fixes #1295

---

include/igl/opengl/ViewerCore.cpp
include/igl/opengl/ViewerCore.h

Reverts libigl/libigl#1318
Two axis should be default

Revert "Set default value for ViewerCore::rotation_type"

---

include/igl/copyleft/tetgen/tetgenio_to_tetmesh.cpp
include/igl/directed_edge_orientations.cpp
include/igl/directed_edge_orientations.h
include/igl/dqs.cpp
include/igl/dqs.h
include/igl/find_cross_field_singularities.cpp
include/igl/find_cross_field_singularities.h
include/igl/marching_tets.cpp
include/igl/marching_tets.h
include/igl/signed_distance.cpp
include/igl/voxel_grid.cpp

Python Bindings Template Fixes 2.0

---

include/igl/active_set.h

Update reference link in active_set

---

.github/workflows/continuous.yml
.github/workflows/nightly.yml

Fix CI build for Nightly jobs.

Dot not build tutorials in Debug mode.

---

include/igl/readCSV.cpp

Bug fix in csvreads. (Bug #1423)

---

.github/issue_template.md
include/igl/SortableRow.h
include/igl/uniformly_sample_two_manifold.h

- [ x] This is a minor change.

Fixes build with mingw-w64

---

.github/workflows/continuous.yml
.github/workflows/nightly.yml

Try to fix CI build on Windows.

---

cmake/LibiglFolders.cmake
include/igl/direct_delta_mush.cpp
include/igl/direct_delta_mush.h
tests/include/igl/direct_delta_mush.cpp
tutorial/408_DirectDeltaMush/CMakeLists.txt
tutorial/408_DirectDeltaMush/main.cpp
tutorial/CMakeLists.txt

Implemented Direct Delta Mesh Skinning (Variant 0) from "Direct Delta Mush Skinning and Variants". Added tutorial example (`408_DirectDeltaMush`).

Direct Delta Mush implementation

---

include/igl/blkdiag.cpp
include/igl/blkdiag.h
tests/include/igl/blkdiag.cpp

Surprised we didn't already have this.

blkdiag function

---

include/igl/PI.h
include/igl/kelvinlets.cpp
include/igl/kelvinlets.h
include/igl/unproject_onto_mesh.h
tutorial/409_Kelvinlets/CMakeLists.txt
tutorial/409_Kelvinlets/main.cpp
tutorial/CMakeLists.txt

Implements the Kelvinlets sculpting brushes
[Demo here](https://streamable.com/77f8xf)

Add Kelvinlet deformations

---

.github/workflows/continuous.yml
.github/workflows/nightly.yml
cmake/LibiglDownloadExternal.cmake

Update compiler version in github actions.

---

include/igl/read_triangle_mesh.cpp

support msh in read_triangle_mesh

---

include/igl/slim.cpp

Missing break in slim (#1641)

---

include/igl/readMESH.cpp
tests/include/igl/readMESH.cpp

Fixes #1678 and #811 and adds some simple tests.

fix readMESH issues; add test

---

.github/workflows/continuous.yml
.github/workflows/nightly.yml

Update job name in github actions.

---

cmake/LibiglDownloadExternal.cmake

Update ImGui to 1.81+

---

.github/workflows/continuous.yml
.github/workflows/nightly.yml

Update github actions.

---

include/igl/embree/EmbreeRenderer.cpp
include/igl/embree/EmbreeRenderer.h

Templates EmbreeRenderer if, for example, the meshes are already float.

template embree renderer

---

include/igl/readPLY.cpp

I think the title and diff speaks for themselves :)

Close files opened by read_triangle_mesh

---

include/igl/triangle/scaf.h

Uninitialized variable (#1852)

---

include/igl/readPLY.cpp
tests/include/igl/readPLY.cpp

Fixes an error in readPLY when per-face data was incorrectly read.
Fixed the error in readPLY function and added a test case.

Fixed incorrect reading of per-face data from PLY file

---

include/igl/IndexComparison.h
include/igl/fast_winding_number.cpp
include/igl/octree.cpp

This just removes a couple of unnecessary includes.

Header cleanup

---

include/igl/triangle/triangulate.cpp
include/igl/triangle/triangulate.h

(This branch got stale; not sure if it ever passed CI, let's see)

Expose edges so that edge markers are actually useful in triangulate output

---

.github/workflows/continuous.yml

Limit global parallelism to 1 with ninja (`cmake --build build -j1`).

Update Windows action.

---

cmake/recipes/external/glad.cmake
include/igl/opengl/gl.h
include/igl/opengl/glfw/Viewer.cpp
include/igl/opengl/glfw/background_window.cpp

Update glad backend.

---

include/igl/opengl/ViewerData.cpp

allow 2d set_edges

---

include/igl/slice.cpp

use vector ()

---

include/igl/bfs_orient.cpp
include/igl/ceil.cpp
include/igl/cumprod.cpp
include/igl/cumsum.cpp
include/igl/dqs.cpp
include/igl/embree/bone_visible.cpp
include/igl/embree/reorient_facets_raycast.cpp
include/igl/floor.cpp
include/igl/gaussian_curvature.cpp
include/igl/histc.cpp
include/igl/in_element.cpp
include/igl/per_face_normals.cpp
include/igl/project_to_line.cpp
include/igl/project_to_line_segment.cpp
include/igl/signed_distance.cpp

Fixes #2149
There's a few commented out to hint at where a reduction needs to go if someone ever gets around to using the more elaborate parallel_for overload for those.

Remove omp pragmas

---

include/igl/is_border_vertex.cpp
include/igl/is_irregular_vertex.cpp

Fix bug in is_irregular_vertex

---

include/igl/readMSH.cpp
include/igl/readMSH.h
tests/include/igl/readMSH.cpp

support rowmajor in readmsh

---

include/igl/readMESH.cpp

Fixes #1680 
Appears to fix both the issues in that file.

read blank lines as comments

---

include/igl/euler_characteristic.h
tests/include/igl/euler_characteristic.cpp

Tests to confirm the Euler characteristic and documentation referencing issue #2249

Euler Characteristic tests

---

include/igl/opengl/ViewerData.cpp

Remove extra calls to set_face_based

---

tutorial/114_CustomShader/main.cpp
tutorial/906_TrimWithSolid/main.cpp
tutorial/CMakeLists.txt

Custom Shader tutorial

---

include/igl/writeOFF.cpp
tests/include/igl/writeOFF.cpp

writeOFF for quads etc.

---

cmake/recipes/external/libigl_tests_data.cmake
cmake/recipes/external/libigl_tutorial_data.cmake

Seems like a typo, but if @jdumas had a reason for calling these "tata" instead of "data" please let me know.

tata -> data

---

include/igl/eigs.cpp
include/igl/spectra/lscm.cpp

Fixes a compile error when checking for not returning a value.

fix compile error

---

include/igl/signed_distance.cpp

missing break

---

include/igl/split_nonmanifold.cpp

fix debug bug: ndef instead of def

---

include/igl/split_nonmanifold.cpp

Fixes #2373
I had a left a comment with a claim that appears to be non-true. The new change doesn't affect the behavior if that claim was true, but fixes this case. In a world where I had more time, I'd investigate if this seemingly false claim implies other flaws.

fix merge of non shared edges

---

include/igl/exterior_edges.cpp
include/igl/split_nonmanifold.cpp
include/igl/unique_sparse_voxel_corners.cpp

Fixes bad templating that was breaking the python build. Not sure how this was ever compiling 🙃

fix bad templating breaking python build
