libigl/libigl

include/igl/embree/unproject_onto_mesh.cpp
include/igl/embree/unproject_onto_mesh.h

Added overload that returns barycentric coordinates of hit instead of vid of closest vertex of hit

Added overload that returns barycentric coordinates of hit

---

include/igl/writeOBJ.cpp

Thats a bug, isn't it? At least it is not consistent with readOBJ(...).

Removed flipping of texture coordinates in writeOBJ(...)

---

include/igl/file_dialog_open.cpp
include/igl/file_dialog_save.cpp

Minor changes to "file_dialog_open.cpp" and "file_dialog_save.cpp" eliminated two similar error messages:
error: #elif with no expression #elif _WIN32
when trying to compile Example 102_DrawMesh with g++ in Cygwin on Windows Vista.
(Not 100% sure these changes are correct though.)

Changes in "file_dialog_open.cpp" and "file_dialog_save.cpp" to help compilation in Vista

---

tutorial/504_NRosyDesign/CMakeLists.txt
tutorial/505_MIQ/CMakeLists.txt
tutorial/506_FrameField/CMakeLists.txt
tutorial/cmake/FindLIBCOMISO.cmake

FindLIBCOMISO.cmake re-defined (expanded) the variable LIBCOMISO_INCLUDE_DIR every time it was called by adding a sub-directory. This leads to a "recursive" expansion of LIBCOMISO_INCLUDE_DIR, which was probably not intended. Instead I would recommended to write such additional include directories into a new variable (LIBCOMISO_INCLUDE_DIRS) and use this instead. I also added additional search paths for finding the library.

FindLIBCOMISO include directory fix

---

include/igl/writeOBJ.cpp

Hi,
Small bug with serialization into obj format

write object bug: need newline between end of v and start of f

---

include/igl/file_dialog_open.cpp

"buffer[pos] = 0" probably should be moved out of the if block, because if a user opens a dialog but press "ESC", then line 64 judgement fails. But "buffer[pos] = 0" should still be set, otherwise line 86 will not return an empty string.

fixed a bug concerning load mesh from dialog

---

include/igl/active_set.cpp
tutorial/706_FacetOrientation/main.cpp

When ACTIVE_SET_CPP_DEBUG is defined, the #warning preprocessor directive is used which
is not supported by Microsoft Visual C++.

Build fix for Microsoft Visual C++

---

include/igl/copyleft/cgal/string_to_mesh_boolean_type.cpp

The special characters "∪","∩","∆" hinder the file to be compiled with msvc. For UTF-8 files which contain such special characters, only UTF-8 with BOM is allowed.

Convert the file string_to_mesh_booean_type.cpp to UTF8-BOM

---

include/igl/harmonic.cpp
include/igl/harmonic.h
tutorial/401_BiharmonicDeformation/main.cpp
tutorial/402_PolyharmonicDeformation/main.cpp
tutorial/403_BoundedBiharmonicWeights/main.cpp
tutorial/501_HarmonicParam/main.cpp
tutorial/503_ARAPParam/main.cpp

- added a boolean `use_cotan_weight` to indicate use the cotangent weights or uniform weights laplacian operator. (`true` means use cotangent weights)
- also modified function calls in tutorial 401 402 501 503

add option for uniform laplacian operator in harmonic mapping function

---

python/iglhelpers.py

Numpy arrays are might not be contiguous.
- add check flag c-contiguous on p2e
- add order flag on e2p
- tested python tutorial 001_BasicTypes.py

Add c-contiguous order to p2e/e2p helper functions

---

include/igl/sortrows.cpp
include/igl/unique.cpp

Trying to squeeze some performance gain from the ``unique_rows`` method.  Summary of changes:
* Avoid call ``.size()`` ``.rows()`` ``.cols()`` repeatedly.
* Use lambda instead of comparison functor, which also avoids copying the array.
* Avoid range checking in comparison method.
* Avoid reversing the array, get it sorted correctly in the first run.
The performance gain is around 25% measured on my macbook air.

Minor speed up of ``unique_rows``

---

include/igl/copyleft/tetgen/tetrahedralize.cpp

* assign a error code `3` for failures.

Fix `igl::copyleft::tetgen::tetrahedralize` to return `0` when it succeeded

---

include/igl/lscm.cpp

Bug discovered using lscm as an initial guess for arap revealed mesh flipping. Inverting the setting of V_uv fixes the issue. See bug #91

Fix mesh orientation flip error in lscm 

---

include/igl/png/render_to_png.cpp

- fixed data size to consider the 4 channels (Red, Green, Blue, Alpha)
- fixed stride_in_bytes to consider the 4 channels

[bug] render_to_png wrong data size

---

include/igl/readSTL.cpp

I think the STL file was closed twiced. This occurs an errors in my case.

*fix bug: stl file is closed twiced when reading ascii

---

include/igl/xml/serialize_xml.cpp

It seems tinyxml2 has discarded the enum ``XML_NO_ERROR``.  Switch it to ``XML_SUCCESS`` to avoid compilation errors.

Minor update to tinyxml2 enum.

---

shared/cmake/FindMATLAB.cmake

There is an error when running cmake for the MATLAB extensions with MATLAB R2016b at the moment. This should fix it.

Added R2016b to MATLAB versions

---

python/py_doc.cpp
python/py_doc.h
python/py_igl.cpp
python/py_igl/py_remove_duplicate_vertices.cpp
python/python_shared.cpp

Python bindings for remove_duplicate_vertices() function.
Tested in python2.7 and 3.5 on GNU/linux

Python bindings for remove_duplicate_vertices()

---

include/igl/writeDMAT.cpp

i found an error in writing binary dmat file.
i tried change "w" to "wb" in fopen and it works.

change "w" to "wb" in fopen to fix the binary dmat writing error

---

include/igl/point_simplex_squared_distance.cpp
include/igl/point_simplex_squared_distance.h
include/igl/seam_edges.cpp

seam_edges was returning duplicate boundary edges. It also has a helper function in an anonymous namespace, which is against the style guide. That has been moved to a lambda.

seam_edges.cpp fixed duplicate boundary edges bug and removed helper

---

include/igl/viewer/ViewerCore.cpp

Solve a small signed/unsigned warning in ViewerCore.cpp.

Solve minor warning in Viewer

---

include/igl/viewer/Viewer.cpp

Remove another warning due to an unused variable in Viewer.cpp.
Not sure if variable ```global_KMod``` has still any utility. I have executed the command:
```sh
find libigl -type f -name "*.cpp" -exec grep "global_KMod" {} \;
find libigl -type f -name "*.h" -exec grep "global_KMod" {} \;
```
and the only reference found is the declaration in line 83. I have removed it just because it shows a warning on every source file including "igl/viewer/Viewer.h"

Remove unused variable in Viewer.cpp 

---

include/igl/boundary_loop.cpp

Fix a crash when calling ```igl::boundary_loop()``` with a mesh without boundary (as "bumpy.off") 
Now, when called with a mesh with no boundary, boundary_loop() returns an empty vector.
Case test:
```cpp
Eigen::MatrixXd V;
Eigen::MatrixXi F;
igl::readOFF("bumpy.off", V, F);
//Compute Boundary Loop
Eigen::RowVectorXi boundary;
igl::boundary_loop(F, boundary);
std::cout<<"Num of boundary vertex: " << boundary.size() << std::endl;
```

Bugfix: boundary_loop crash on meshes without boundary

---

include/igl/AABB.cpp

I had problem compiling AABB with GCC 4.6.3. It seems to be related to this:
http://stackoverflow.com/questions/16007855/gcc-compilation-error-when-using-template-class-method-inside-lambda-expression

Support for older GCC

---

include/igl/upsample.cpp
include/igl/upsample.h

Allows for returning a sparse matrix that can then be multiplied with properties

Make usample work like loop subdivision

---

include/igl/writeOBJ.cpp

In effect, meshes can have an arbitrary number of position dimensions.

writeOBJ writes out as many coordinates per vertex as there are columns in V

---

include/igl/viewer/ViewerCore.cpp

A minor bug, where Eigen doesn't like casting from a temporary. Without the proper brackets, the multiply by 0.5 results in an Eigen temporary type, which doesn't cast well. Changing the order of operations before the eval makes centroid a Vector3f type which can be cast. Also means we can get rid of the extra evals.
Apparently this manifests only in the debug mode in Visual Studio, and is fine in release.

Fixed order of operations bug when computing model transform

---

include/igl/copyleft/cgal/extract_feature.cpp
include/igl/copyleft/cgal/extract_feature.h

Using `CGAL::compare_dihedral_angle` to extract all feature edges with **exact** dihedral angle larger than a given tolerance.
Small print: Dihedral angle is not well-defined for degenerate triangles.  Throw exception if degenerate faces are encountered.

Dihedral angle based exact feature extraction

---

include/igl/vector_area_matrix.cpp

https://github.com/libigl/libigl/issues/441
bazel-out/clang_k8-opt/genfiles/third_party/Eigen/src/SparseCore/SparseCwiseBinaryOp.h:266:62: error: no member named 'outer' in 'Eigen::internal::binary_evaluator<Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, const Eigen::SparseMatrix<double, 0, int>, const Eigen::SparseMatrix<double, 0, int> >, Eigen::internal::IteratorBased, Eigen::internal::IteratorBased, double, double>::InnerIterator'
Scalar rhsVal = m_rhsEval.coeff(IsRowMajor?m_lhsIter.outer():m_id,
~~~~~~~~~ ^
bazel-out/clang_k8-opt/genfiles/third_party/Eigen/src/SparseCore/SparseAssign.h:90:78: note: in instantiation of member function 'Eigen::internal::binary_evaluator<Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<double, double>, const …

Workaround for Eigen-3.3.1:

---

shared/cmake/CMakeLists.txt

Fixes the CMake conflict when enabling NanoGUI in the viewer.

Work-around for GLFW+GLEW+NANOGUI CMake conflict

---

include/igl/AABB.cpp

I ran into an issue where ```AABB::init()``` (with Scalar == float) crashed for a valid but large mesh. It seems that float was not sufficient to store the median element used in the construction, therefore the LI and RI vectors were not filled correctly. Instead of defaulting to double for the median, I would propose to avoid precision issues by directly finding the largest element for LI, which is an int, instead of computing the average of the two middle elements, in case of an even number of elements.

Avoid precision issue in AABB::init()

---

include/igl/grad.cpp

Previously a `Eigen::VectorXd` is assigned with comma initializer

Bug fix in igl::grad_tri(uniform)

---

include/igl/viewer/ViewerCore.h

ViewerCore.h effectively includes gl.h before glew.h which causes compilation errors on Linux. By ensuring OpenGL_state.h is included first, these headers will be included in the proper order.

Fix compilation bug when including ViewerCore.h

---

include/igl/viewer/OpenGL_state.cpp

This minor fix allows the viewer code to render textures with per-corner-uvs
defined even when face_based is set to false. I think the face_based rendering
property shouldn't affect the way UVs should be interpreted.

Allowing per-corner-uvs when face_based rendering is true in viewer. 

---

tutorial/tutorial.md

I needed these two on my fresh ubuntu box. Are they unusual? If not, should we add them to the general instructions?

Add more sudo apt-get install commands

---

include/igl/grad.cpp

`u` is not initialized or computed in the `else` `(uniform == true)` branch at 4 lines below. It can cause some error afterward.

Bug Fix for 2d uniform grad

---

include/igl/readPLY.cpp

Added explicit template instantiations for readPLY() needed when using libigl as a static library.

add needed template instantiations

---

include/igl/viewer/Viewer.cpp
include/igl/viewer/Viewer.h
include/igl/viewer/ViewerCore.cpp
include/igl/viewer/ViewerCore.h
include/igl/viewer/ViewerPlugin.h
python/tutorial/shared.py

Right now from python there is no way to resize the libigl viewer, since the glfw `window` is not exposed. While there was a `resize()` function in the current viewer, this one was pretty much useless since it doesn't set the actual window size, but is just a callback that is run every time the user resizes the window directly.
This PR fixes this issue, and `resize()` now does what you would expect (hopefully working also for high-DPI screens).

Minor improvements to the viewer (resize + 2D mode).

---

python/CMakeLists.txt

The pyigl.so library is placed in ${PROJECT_SOURCE_DIR}, but the post-build strip commands look relative to the ${CMAKE_CURRENT_BINARY_DIR}.  I suspect this isn't an issue when building in source as suggested in the README, but it fails when building in other directories.
The pyigl.so library is placed in ${PROJECT_SOURCE_DIR} via the LIBRARY_OUTPUT_DIRECTORY here: https://github.com/libigl/libigl/blob/aa114dc68cf0aac38bc99c8814ba3c79c96b5243/python/CMakeLists.txt#L140

correct the pyigl.so path given to strip command

---

python/CMakeLists.txt

This PR allows the user to specify their own pybind11 directory at CMake time via the PYBIND11_INCLUDE_DIR cmake variable.   This allows users to avoid problems when importing multiple libraries that use different pybind11 versions, as discussed in #467 
The default value is the included version, so users shouldn't notice any change if they don't manually specify a new pybind11 location.

allow specification of alternate pybind11 directory

---

python/modules/py_typedefs.cpp
python/modules/py_typedefs.h
python/py_doc.cpp
python/py_doc.h
python/py_igl.cpp
python/py_igl/py_adjacency_list.cpp
python/python_shared.cpp
python/scripts/generate_docstrings.py
python/scripts/parser.py

Add python bindings for` igl::adjacency_list (const Eigen::MatrixXd& F, std::vector<vector<int>>& out_list)`.
The python signature is `adjacency_list(F: eigen.MatrixXd)` and returns the adjacency list as a Python list. This return requires copying the vector, out_list, to the returned value. This is unavoidable without either (a) implementing a modified `igl::adjacency_list` to handle Python lists (hacky) or (b) exposing STL vectors as a custom type to python (ugly). Therefore, I believe the extra copy is acceptable.

Add python bindings for igl::adjacency_list

---

include/igl/readOBJ.cpp

Extend readOBJ to support n-dimensional vertex lines, n >= 3
Modification in response to issue #454 enhancement request. readOBJ vertex matrix will contain columns equal to the number of components on the "v ..." .obj file line as encountered.

n-dimensional OBJ vertex support

---

include/igl/vector_area_matrix.cpp

A small change to optimize/simplify the code of vector_area_matrix.
Instead to build two sparse matrix that have to be added and scaled,
build directly the triplets for the sparse result matrix.
Also, do a reserve() before of filling the triplets list.

Simplify vector_area_matrix.cpp

---

matlab-to-eigen.html

On the page of matlab-to-eigen.html, the link to tutorial.html seems to be wrong

Fix a wrong link in matlab-to-eigen.html

---

include/igl/copyleft/marching_cubes.cpp

Convert the edge to key dictionary in marching cubes from an `std::map` to an `std::unordered_map`. I measured a 10-20% performance increase after this change.

Post-Mature Optimization feat. MC Hash

---

shared/cmake/libigl.cmake

Fixes two small issues:
- The option to disable before including `glfw` is called [GLFW_INSTALL](https://github.com/wjakob/glfw/blob/0ff30d648506e19a1c54a2b2a2d09c4e59b86922/CMakeLists.txt#L31), not `GLFW_BUILD_INSTALL`
- Somehow, it seems that linking with `pthread` is needed when using functions that call `parallel_for` (e.g. `igl::doublearea()`). I had a linking error only when I used libigl in header-only mode, which is weird. But asking CMake to properly link against the C++11 thread library fixed it (it links with `pthread` on Unix systems, and the native Windows thread library on Windows).

Small fixes in CMake build script.

---

python/CMakeLists.txt

This PR re-enables use of an alternate pybind11 (It was inadvertently removed in e7d5bc2).   No change unless the user manually specifies the PYBIND11_DIR CMake variable.

enable use of alternate pybind11

---

python/CMakeLists.txt

`target_link_libraries` creates an error in case one do not specify PUBLIC/PRIVATE for each use of `target_link_libraries` on a target
-- LTO enabled
CMake Error at CMakeLists.txt:134 (target_link_libraries):
The keyword signature for target_link_libraries has already been used with
the target "pyigl".  All uses of target_link_libraries with a target must
be either all-keyword or all-plain.

Fixed Python CMakeLists.txt for CMake 3.10.0

---

python/py_igl/copyleft/tetgen/py_tetrahedralize.cpp

This adds Python bindings for the second overload of `tetrahedralize` which allows adding integer markers to input vertices.

expose overloaded version of tetrahedralize in pyigl

---

python/README.md
python/tcpviewer.py
python/tutorial/102_DrawMesh_TCP.py
python/tutorial/702_WindingNumber.py
python/tutorial/704_SignedDistance.py
python/tutorial/705_MarchingCubes.py
python/tutorial/706_FacetOrientation.py
python/tutorial/707_SweptVolume.py
python/tutorial/708_Picking.py
python/tutorial/709_VectorFieldVisualizer.py

Here I fixed some remaining files in python tutorials section, to reflect the recent libigl viewer refactoring and addressing the issue #726 
Just as a note here, 
702_WindingNumber.py is buggy in showing the results, 
704_SignedDistance.py has a segmentation fault.
The functionality in 709_VectorFieldVisualizer.py doesn't exist now.

Update python tutorials to reflect the viewer refactor

---

include/igl/shape_diameter_function.cpp
python/py_doc.cpp
python/py_doc.h
python/py_igl.cpp
python/py_igl/py_shape_diameter_function.cpp

This adds Python bindings for two overloads of `shape_diameter_function`.
On the C++ side, this also implements the missing overload for the `shape_diameter_function(V, F, per_face, num_samples, S)` signature.

Python bindings for shape_diameter_function

---

include/igl/ply.h

During compilation, there's a following warning
```
ply.h:232:13: warning: inline function ‘void ply_get_element(PlyFile*, void*)’ used but never defined [enabled by default]
inline void ply_get_element(PlyFile *, void *);
```
It seems the signature was changed as some point but this line of declaration was left out.

Removing the warning in ply

---

include/igl/copyleft/cgal/remesh_intersections.cpp

Hi!
I'm a student of Professor Jernej Barbic.
My new project is dependent on the mesh boolean routine in libigl and I have found a bug in remesh_intersections.cpp. I have fixed it and created a pull request here.
Previously in the function, if a new vtx is visited when stitch_all==false, it does not handle the case when the vtx is in the interior of a face. This commit fixes that.

fix a bug in remesh_intersections

---

include/igl/slice_into.cpp

This fix replaces `Y.size()` with `Y.rows()` and `Y.cols()` to get the correct behaviour of runtime assertions in `slice_into.cpp`.

Bug fix in slice_into.cpp

---

include/igl/fast_winding_number.h

Just very minor typos/issues in the class documentation. Not sure it deserves a PR but anyway ;)

minor typos in Fast Winding doc

---

tutorial/505_MIQ/main.cpp

Hey guys!
I found a unneeded string in on of the tutorial examples.
Best,
Kacper

Remove a path refering to a non-existing file

---

include/igl/opengl/glfw/Viewer.cpp

I run into an assertion error when running Example 505 (505_MIQ) on my custom mesh (made of an inner surface and a outer surface), and found that comb() function does not support manifold with separated parts.
I did a minor modification: add while loop outside of the flood fill loop, and then it works well. So is it proper to merge into the main repo?

add while loop for comb_cross_field.cpp, making comb support separated manifold

---

tests/include/igl/copyleft/cgal/order_facets_around_edges.cpp

In `igl::copyleft::cgal::order_facets_around_edges`, we need to determine the direction of each undirected edge in order to sort the adjacent facets.  This direction is determined by the first directed edge in `uE2E[i]` list (as shown in [this line](https://github.com/libigl/libigl/blob/master/include/igl/copyleft/cgal/order_facets_around_edges.cpp#L52)).  However, in the unit test, we are using the direction of `uE[i]` as the reference direction.  This inconsistency causes the unit test in `MultipleDuplicatedFaces` test case to fail on linux (`uE[i]` could different on linux and mac, but both are valid since they represent unsigned edge).

Order facets around undirected edge unit test fix

---

include/igl/opengl/glfw/Viewer.cpp

changed hack for Mojave such that it is not running with transparency enabled
fixed a bug on windows when minimising the window.
Unfortunately not tested on windows

Macos Mojave different hack and Windows minimisation fix

---

include/igl/copyleft/comiso/miq.cpp

There is no need to loop over the elements to set them up. Normally, even without giving the value (as I did) the values should be set to 0. On the other hand, std::fill() should be used instead of looping over a container.
- [-] Adds new .cpp file.
- [-] Adds corresponding unit test.
- [-] Adds corresponding python binding.

Avoid a loop

---

include/igl/opengl/glfw/imgui/ImGuiTraits.h

Change `char * format` to `char format []` to fix compilation error when using VS2017.

compilation error fix

---

include/igl/cotmatrix_intrinsic.h

Noticed a bug while looking at the new dev branch, `cotmatrix_intrinsic.h` references the wrong cpp so it gives errors in compile in header-only.

fix wrong reference in cotmatrix_intrinsic

---

cmake/LibiglDownloadExternal.cmake

Current version of glfw produces the following warning with recent versions of CMake:
```
CMake Deprecation Warning at external/glfw/CMakeLists.txt:10 (cmake_policy):
The OLD behavior for policy CMP0042 will be removed from a future version
of CMake.
The cmake-policies(7) manual explains that the OLD behaviors of all
policies are deprecated and that a policy should be set to OLD only under
specific short-term circumstances.  Projects should be ported to the NEW
behavior and not rely on setting a policy to OLD.
```
The new version has CMake 3.0 as minimum version instead of 2.8.12, but that's ok since our CMake requires 3.1.

Bump version of glfw.

---

include/igl/opengl/ViewerData.h

https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html
A memory alignment assertion fired once for the .data_list in the viewer. I'm not sure if we also need the special stl vector allocator for the data list of if this is enough to fix it. It's hard to get this assertion to fire in a reproducible way.

Eigen Alignment issue

---

README.md

We ought to keep this warning sign for at least 6 months. It's best to have it on the github readme as well (#992), so it should be merged into `master`.

Warning about rewritten history (fix #992).

---

include/igl/copyleft/cgal/wire_mesh.cpp

In #963, I asked about flattening the caps on any terminal vertices of wiremeshes. Following @alecjacobson's implementation suggestions, I zero out the offset when a vertex is incident on only one edge.

Flatten wiremesh caps when vertex on single edge.

---

cmake/LibiglDownloadExternal.cmake
tests/include/igl/cut_to_disk.cpp

Added a failing unit test for `igl::cut_to_disk` based on https://github.com/libigl/libigl/pull/984.

Add cut to disk unittest

---

include/igl/copyleft/cgal/mesh_to_polyhedron.cpp
include/igl/copyleft/cgal/mesh_to_polyhedron.h
include/igl/hausdorff.h

The origin version only accepts Eigen::MatrixXd as vertices.
Add a template parameter to `igl::copyleft::cgal::mesh_to_polyhedron` so it also accepts `Eigen::MatrixXf` as `V`

Building a CGAL polyhedron via a float-type Eigen matrix.

---

include/igl/remesh_along_isoline.h

"remesh_along_isoline.cpp" instead of "remesh_along_isoline.h" shall be included.
The original code triggers a "symbol not find" error at the linking stage.

Fix the typo in a `#include` statement.

---

tests/include/igl/cotmatrix.cpp

Use matrix multiplication to compute sum rather than for loop.

Fix cot matrix unit test to avoid Eigen bug

---

.travis.yml
cmake/DownloadProject.CMakeLists.cmake.in
cmake/LibiglDownloadExternal.cmake

Seems that yesterday Travis updated their macOS image or something, and as a result the `brew install ccache` command was failing. Looks like using the `homebrew` addon to install `ccahe` is a better option.
I've also simplified a bit the Travis script and added a CMake option to make @evouga happy (#1068).

Fix Travis build + minor CMake improvements.

---

include/igl/min_quad_with_fixed.cpp

I was working on a project, and I noticed I couldn't compile something like this when all the variables had `float` template types:
```
Eigen::SparseMatrix<float> Q, Aeq;
Eigen::VectorXi b;
Eigen::VectorXf bc, B, Beq, Z;
...
igl::min_quad_with_fixed_data<float> mqwf;
igl::min_quad_with_fixed_precompute(Q, b, Aeq, true, mqwf);
igl::min_quad_with_fixed_solve(mqwf, B, bc, Beq, Z);
```
This PR fixes the compile errors I encountered.
I'm not exactly how to unit test this, unless you'd like me to upload some code and verify that it compiles.

fix min_quad_with_fixed to work for non-double template types

---

cmake/LibiglDownloadExternal.cmake

As noted in https://github.com/libigl/libigl-stb/pull/2:
Compiling igl_stb_image with gcc 7.3 (Ubuntu 18.04 LTS) with `-Wall` creates many warnings, like
```
libigl/external/stb/stb_image.h: In function ‘unsigned char* stbi__convert_format(unsigned char*, int, int, unsigned int, unsigned int)’:
libigl/external/stb/stb_image.h:1361:44: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
#define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
^
```
These warnings have been fixed upstream in stb_image and stb_image_write, thus I propose to update these files to their current versions from nothings/stb master. Compiling with these versions runs warnings-free.

Bump stb_image version

---

include/igl/boundary_loop.cpp

Explicit template instantiation of std::vector<std::vector<int>> for boundary_loop

Explicit template instantiation of std::vector<std::vector<int>> for boundary_loop

---

cmake/libigl-config.cmake.in

This PR fixes #1100.
Also refactored the code to locate Eigen3.
Successfully tested the following scenarios
1. Eigen3::Eigen present in the project before calling `find_package(libigl CONFIG REQUIRED)`
2. Eigen3::Eigen not present but locatable using `find_package`
3. Eigen3::Eigen not present and not locatable using `find_package` but by using `pkg-config'
3. Eigen3 cannot be found in any way -> correctly issues an error.

Fix: Wrong Eigen3 dependency when using find_package(libigl) #1100

---

include/igl/knn.cpp

Fixed runtime error with MSVC STL in Debug builds. Release builds do not check if the comparator is valid (needs to be a strict weak ordering, where `!comp(a, b) && !comp(b, a)` means that `a` and `b` are equivalent).

[knn] Fixed comparison functor in priority queue

---

include/igl/scaf.cpp
tests/include/igl/cotmatrix.cpp
tests/include/igl/cotmatrix_entries.cpp

In my windows environment with ~~VS2010~~ (Edit: VS2017), I get build errors due to unknown constant `M_PI`. Since `igl/PI.h` defines this constant internally, I replaced all references to `M_PI` in the code with `igl::PI`. I suppose this is the intended use anyhow.
After these changes, I can successfully run the build on my machine.
- [ x] This is a minor change.

Ensured use of internally defined constants.

---

include/igl/serialize.h

In the deserialization functionality of libigl, a return value indicating the success of the deserialization is ignored. As a result, the deserialization from a file always returns a success, as long as the file can be opened. With the change in this commit, a success is only returned if the file can be read **and** the variable could be deserialized.

Corrected omission of return argument.

---

include/igl/randperm.cpp
include/igl/randperm.h
tests/include/igl/randperm.cpp
tests/test_common.h

Now that I can wrap my head around forwarding references and reference collapsing rules, I realize there was a minor bug introduced in #1062, leading to `igl::randperm` not consuming the generator as intended. Now repeated calls will generate different permutations.

Fix logic error for URNG in igl::randperm

---

cmake/LibiglDownloadExternal.cmake

Now we use .cpp files from upstream for the glfw+opengl3 bindings of ImGui, so this should make it easier to keep up with changes from upstream imgui =)

Updates ImGui dependency to 1.69

---

include/igl/copyleft/marching_cubes.cpp

The sparse index version of marching cubes was trying to access an Eigen vector like a std::vector, preventing compilation.

Fixing bug preventing compilation of sparse marching cubes

---

include/igl/remesh_along_isoline.h

- Fix typo in the header documentation
- Solve linker error caused by typo in the bottom of the header file (including wrong file)

Bugfix in remesh_along_isoline.h

---

include/igl/ply.h
include/igl/xml/serialize_xml.cpp

As mentioned in #919 the ply.h implementation has several code quality issues. The suggested changes fix two memory leaks. One is caused by a missing free, another from improper handling when realloc fails. Additionally UB has been identified, because a pointer to a local variable is returned.

Fixed two memory leaks

---

include/igl/octree.cpp
include/igl/remesh_along_isoline.h

For translating centre, the distance should be the half of width of the sub cell instead of the width h.

Fix a issue in octree.

---

include/igl/opengl/glfw/Viewer.cpp
include/igl/opengl/glfw/Viewer.h
python/modules/py_igl_opengl_glfw.cpp

See #1166 and #1167 for more details.

Viewer const accessors + use viewport size (fixes #1166, fixes #1167).

---

include/igl/sort_triangles.cpp
include/igl/sort_triangles.h

Fix templating in sort_triangles

---

include/igl/signed_distance.cpp

Changed `size_t` → `std::ptrdiff_t` for OpenMP2.0 compatibility; now compiles without issue on MSVC

✨ Enable OpenMP for MSVC users (#1147)

---

python/modules/py_igl_opengl_glfw.cpp

Due to the changes in glfw::Viewer one should pass a parameter when calling data() to select a mesh. In C++ mesh_id=-1 by default ( the last element). This commit adds this behaviour for the python bindings.
For corresponding C++ code see: https://github.com/libigl/libigl/blob/dev/include/igl/opengl/glfw/Viewer.h#L91
This fixes #1211 and makes the previous usages of ` igl.glfw.Viewer().data()` python code work again.

Default arg for igl.glfw.Viewer().data() => mesh_id -1

---

include/igl/path_to_executable.cpp
tests/include/igl/path_to_executable.cpp

Added symboles to check for in path_to_executable() because capital case UNIX is not defined under Linux (i.e. Ubuntu).
Lowercase unix is defined however. See: https://stackoverflow.com/questions/142508/how-do-i-check-os-with-a-preprocessor-directive
Also added missing include for readlink().
readlink() does not append a null byte, thus use information about the written byted when building the resulting string.

Fix on linux path_to_executable()

---

python/modules/py_igl_opengl_glfw.cpp
python/tutorial/103_Events.py
python/tutorial/205_Laplacian.py
python/tutorial/401_BiharmonicDeformation.py
python/tutorial/402_PolyharmonicDeformation.py
python/tutorial/403_BoundedBiharmonicWeights.py
python/tutorial/404_DualQuaternionSkinning.py
python/tutorial/405_AsRigidAsPossible.py
python/tutorial/501_HarmonicParam.py
python/tutorial/502_LSCMParam.py
python/tutorial/503_ARAPParam.py
python/tutorial/505_MIQ.py
python/tutorial/606_AmbientOcclusion.py
python/tutorial/607_ScreenCapture.py
python/tutorial/609_Boolean.py
python/tutorial/704_SignedDistance.py
python/tutorial/707_SweptVolume.py
python/tutorial/708_Picking.py
python/tutorial/709_VectorFieldVisualizer.py

Expose igl.glfw.Viewer.core() the same way as in C++ and set defallt argument.
Replace 'viewer.core' with 'viewer.core()' in python tutorials. Use same API style like in C++. (However some other functions for multiple viewport support do not have python bindings.)
Together with #1220 this fixes #1225 
Tested various other python tutorials, they seam to work now.

Python: igl.glfw.Viewer().core => igl.glfw.Viewer().core() with default arg unsigned core_id = 0

---

include/igl/file_dialog_open.cpp
include/igl/file_dialog_save.cpp

Attempt to fix several issues with the libigl file dialogs, so that they correctly return an empty string rather than garbage when:
- the user cancels the dialog
- the user selects a file somehow longer than the 1024-character limit
- the file selection using zenity etc. fails for any other reason.
There is a strange erasure of the last character in the Linux version
(presumably to remove some trailing newline?) that I did not touch.
Fixes #1209.

file_dialog_open/save fixes

---

.travis.yml
include/igl/is_irregular_vertex.cpp
tests/include/igl/is_irregular_vertex.cpp

Only in DEBUG mode Eigen does all boundary checks when accessing elements.
Thus when using `igl::is_irregular_vertex()` fails if `CMAKE_BUILD_TYPE=Debug`.
I've added a test for igl::is_irregular_vertex to showcase that it segfaults with CMAKE_BUILD_TYPE=Debug due to a missing F.maxCoeff()+1 in https://github.com/libigl/libigl/blob/master/include/igl/is_irregular_vertex.cpp#L16 see build https://travis-ci.org/BruegelN/libigl/builds/550519463 (Note only macOS builds with `CMAKE_BUILD_TYPE=Debug` and it's not related to the recent changes on Travis CI for macOS)
After fixing the off-by-one issue everything works as expected (https://travis-ci.org/BruegelN/libigl/builds/550521102)

Fix igl::is_irregular_vertex()

---

.travis.yml
CMakeLists.txt
cmake/HunterGate.cmake
cmake/libigl-cgal.yml
cmake/libigl.cmake
include/igl/deprecated.h
include/igl/is_irregular_vertex.cpp
tests/include/igl/is_irregular_vertex.cpp

Original PR with missing branch here: #1202 
This PR adds basic support for the Hunter package manager in libigl. Because libigl is already following modern CMake practices, the changes needed to make this package Hunter-ready are minimal.
Changes:
1) Add `HunterGate.cmake` and corresponding CMake code in `CMakeLists.txt`
2) Pull `Eigen` from Hunter
3) Add `HUNTER_ENABLED` flag and default to `OFF` to preserve current behavior.
Once this change is merged, a new (minor?) GitHub release is needed to generate a source tarball that Hunter can pull in.

Hunterize libigl, attempt 2

---

include/igl/opengl/ViewerData.cpp

set dirty flags for specular and ambient too inside igl::opengl::ViewerData::set_colors().

---

include/igl/readSTL.cpp

valgrind reported undefined behaviour while using readSTL.cpp. This simple change ensures no uninitialized data is read while reading the header line in readSTL.cpp
- [x ] This is a minor change.

Avoid reading beyond boundaries of arrays in readSTL.cpp

---

include/igl/copyleft/cgal/orient2D.h

Typo in documentation in orient2D

---

tutorial/710_SCAF/main.cpp

* Fix a potential crash when initializing the map for meshes with holes
* Fix a minor conversion warning
Without this change we can get crashes on models with holes.

Fix a potential crash when initializing the map for meshes with holes

---

include/igl/dijkstra.cpp
include/igl/dijkstra.h
tests/include/igl/dijkstra.cpp

Currently, the functions in Dijkstra either does uniform weight BFS or has a weird per-vertex weight. 
This commit adds the overload to use mesh edge length.
I also add a small test file for it.
- [x ] Adds corresponding unit test.
- [x ] This is a minor change.

Use edge length from mesh in  `igl::dijkstra`.

---

include/igl/opengl/ViewerCore.h

Fix a complaint from Valgrind.
During the initialization of `ViewerCore::ViewerCore()`, `set_rotation_type` is called where value of  `rotation_type` is a value used without initialization.

Set default value for ViewerCore::rotation_type

---

tutorial/105_Overlays/main.cpp

`ViewerData::show_labels` exists since #1196 and is `false` by default, thus turn it on for tutorial 105.
previously:
now:

activate label rendering for tutorial 105 overlays.

---

include/igl/heat_geodesics.cpp

Hello, I tested the fix by @xinyazhang on #1230 and #1237 in my environment (VS2017/Windows 10). Unfortunately, it still doesn't work for me. I checked it with the debugger and found that Aeq is still empty after running the original line of code (maybe this should be Eigen bug).  
To fix this, I made one additional line to create M.diagonal().transpose() and make it sparse representation in the second line. Additionally, I also set the type as Scalar, not "double" to follow the original template.  
I certificated that it now works in my environment.

# fix issue #1237

---

include/igl/ray_box_intersect.cpp
include/igl/ray_mesh_intersect.cpp

While profiling PrusaSlicer, I bumped into a severe performance bottleneck with repeated memory allocations where a simple array is suitable or a `reserve()` can be called on the used vector. The algorithm which uses the changed routines now runs approximately 10x faster and the performance is uniform across Win64, Linux and Mac platforms.

Fix performance bottleneck caused by unnecessary  memory allocations.

---

include/igl/copyleft/comiso/nrosy.cpp
tutorial/504_NRosyDesign/main.cpp

The current nrosy implementation is not consistent with the MIQ paper, and the singularity index has wrong sign. This PR is to fix this.

update nrosy to match the MIQ paper

---

include/igl/is_irregular_vertex.cpp

Output vector was one too short for is_irregular_vertex. It is still broken for quad meshes since it relies on is_border_vertex, which does not work for quad meshes due to using triangle_triangle_adjacency.

Fix is_irregular_vertex for triangle meshes

---

include/igl/marching_tets.cpp

J was not always being filled in and then it was erroneously resized to the wrong length. This most immediately _**broke**_ the WindingNumber tutorial.

Bug fix in marching_tets

---

cmake/LibiglDownloadExternal.cmake
include/igl/HalfEdgeIterator.cpp
include/igl/cut_mesh.cpp
include/igl/cut_mesh.h
tests/include/igl/cut_mesh.cpp

Current implementation of cut_mesh function add duplicated vertices directly after the original one. Breaking the original indices of vertices is undesirable sometimes. This new function will append all new vertices at the bottom of V matrix and provides an index mapping to find the correspondence after cut.
Added some simple unit test. Since the mapping of indices changed, the test data for MIQ needs to be updated.

cut mesh refactor

---

include/igl/heat_geodesics.cpp

Heat Geodesics first computes a scalar potential field. Values far from the source will be extremely small, approaching the limits of floating point numbers. Then the method takes the per triangle gradient and _normalizes_ this vector (divides the vector by the norm).
The gradient vector will have <sub>tiny</sub> values. (e.g., [1e-300 2e-300 3e-300]). Computing the vector norm in the obvious way will fail. [It's more robust to first divide by the coordinate with the max absolute](http://www.alecjacobson.com/weblog/?p=4695) and then take the norm.

Fix underflow issue when computing normalization

---

cmake/LibiglDownloadExternal.cmake
include/igl/predicates/predicates.cpp
include/igl/predicates/predicates.h

Might as well make this function thread-safe... Doesn't hurt.

Thread-safe predicate initialization using singleton pattern.

---

include/igl/all_edges.h
include/igl/boundary_loop.cpp
include/igl/cross_field_mismatch.cpp
include/igl/deprecated.h
include/igl/find_cross_field_singularities.cpp
include/igl/internal_angles.h
include/igl/is_border_vertex.h
include/igl/is_irregular_vertex.cpp
include/igl/line_field_mismatch.cpp
include/igl/nchoosek.h
include/igl/readOBJ.h
include/igl/remove_duplicates.h

* Use the macro in `igl::all_edges`, `igl::internal_angles` and `igl::is_border_vertex`.
CTRL+F for "deprecated" to find functions where the comment says they're deprecated.
* Removed #include deprecated.h for `igl::nchoosek` and `igl::readOBJ` because it looks like the functions which have been marked as deprecated are already gone. See [igl::nchoosek](https://github.com/libigl/libigl/commit/471f0c9c37478120dd910bef84bbe87fd96fcaa7#diff-f56795cb8c2b945d68d392cb5d89688e) and [igl::readOBJ](https://github.com/libigl/libigl/commit/dcd8c80fbc71cc85050f4875025b646aeda572c9#diff-e0dd9ddd2a25dde223acf9d1252f437f)
The compiler warning will look sth. like below if you use a deprecated func.
```bash
std::vector<bool> igl::is_border_vertex(const Eigen::MatrixBase<Derived>&, const …
```

Make use of IGL_DEPRECATED

---

cmake/libigl.cmake

Without this PR, if you simply link to igl and include svd3x3.h, you will get the below error
```
/usr/include/igl/svd3x3.cpp:18:10: fatal error: Singular_Value_Decomposition_Preamble.hpp: No such file or directory
#include "Singular_Value_Decomposition_Preamble.hpp"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
and it is because the .hpp files are not installed along with the .h files. This PR fixes it and now I can include svd3x3.h without a problem.

install missing hpp files

---

include/igl/hsv_to_rgb.cpp
include/igl/hsv_to_rgb.h

The previous behavior of hsv_to_rgb is to map positive hue values to the range [0, 360], but does not do the same thing for negative values, instead returning a random result (uninitialized variables). This change causes hsv_to_rgb to always map the input hue to [0, 360].
Closes #1397.

Allows hsv_to_rgb to work on negative hues

---

include/igl/average_onto_faces.cpp

Added igl:: to average_onto_faces.cpp
Might solve libigl/libigl-python-bindings#35

Added igl namespace average_onto_faces.cpp

---

include/igl/is_stl.cpp

detected by running with ASAN in all_meshes test. Made sure that string is zero terminated.

Fixes stack overwriting bug in gl::is_stl, when file have binary data

---

include/igl/copyleft/cgal/extract_cells.cpp

From the context it seems this line should be numeric_limits::lowest() since numeric_limits::min() refers to the minimal positive number (2.22507e-308) in the double range, instead of the lowest number (-1.79769e+308) in the double range. This bug would cause incorrect computation of the bounding box.

numeric_limits<double>::min() is the minimal positive number

---

include/igl/opengl/glfw/Viewer.cpp

Iterate over viewer.core_list and viewer.data_list and align_camera_center per core with visible data
Previously with `core().align_camera_center(data().V,data().F);` the alignment wasn't done properly with multiple meshes and ViewerCores if the meshes had different centers and/or scale.
MWE:
```C++
#include "tutorial_shared_path.h"
#include <igl/opengl/glfw/Viewer.h>
#include <string>
#include <iostream>
int main(int argc, char * argv[])
{
igl::opengl::glfw::Viewer viewer;
viewer.load_mesh_from_file(std::string(TUTORIAL_SHARED_PATH) + "/snail.obj");
viewer.load_mesh_from_file(std::string(TUTORIAL_SHARED_PATH) + "/cube.obj");
unsigned int left_view, right_view;
int cube_id = viewer.data_list[0].id;
int sphere_id = viewer.data_list[1].id;
viewer.callback_init = …
```

fix align_camera_center in Viewer::init() for multiple cores

---

include/igl/serialize.h

So far, the serialization functionality is implemented only for Eigen::Matrix and Eigen::SparseMatrix. This commit duplicates the Eigen::Matrix code for Eigen::Array.
Perhaps Eigen::DenseBase can be used to prevent code repetition.
There do not seem to be any unit tests for the serialization functionality, thus none were added.

Extended serialization functionality to Eigen::Array.

---

.github/workflows/continuous.yml
.github/workflows/nightly.yml

Currently some actions fail because of the limited clone depth. This is only a problem when merging/pushing multiple commits on a branch when there are other jobs running. I think a depth of 10 should be enough for most situation, but we can always change that.

Update clone depth.

---

include/igl/opengl/MeshGL.cpp
include/igl/opengl/ViewerCore.cpp
include/igl/opengl/ViewerData.cpp
include/igl/opengl/ViewerData.h
include/igl/opengl/glfw/Viewer.cpp

Add an option to display with double sided lighting. Helpful for poorly oriented models (like the truck in our test data) or for meshes that are the mid-surface of thin shape (rather than boundary of solid region).

Toggle double sided lighting

---

tests/main.cpp

Changes introduced in #1001 cause unit tests in debug mode to fail, since it seems some floating-point exceptions are now raised. Let's just comment it out until we fix the actual unit tests which are causing this.

Comment FPE for now.

---

include/igl/opengl/MeshGL.cpp
include/igl/opengl/ViewerCore.cpp
include/igl/opengl/ViewerData.cpp
include/igl/opengl/ViewerData.h
include/igl/opengl/glfw/Viewer.cpp

Texture slot can be used as a material capture (also known as environment map). Swapping in a [matcap](https://github.com/nidorx/matcaps) from an image is very simple.
Here's a minimal example
```
#include <igl/opengl/glfw/Viewer.h>
#include <igl/read_triangle_mesh.h>
#include <igl/png/readPNG.h>
int main(int argc, char *argv[])
{
igl::opengl::glfw::Viewer v;
Eigen::MatrixXd V;
Eigen::MatrixXi F;
igl::read_triangle_mesh(argv[1],V,F);
Eigen::Matrix<unsigned char,Eigen::Dynamic,Eigen::Dynamic> R,G,B,A;
igl::png::readPNG(argv[2],R,G,B,A);
v.data().set_mesh(V,F);
v.data().set_texture(R,G,B,A);
v.data().use_matcap = true;
v.data().show_lines = false;
v.launch();
}
```
For example, then
`./main beetle.off Chrome.png` will produce
[Chrome.png.zip](https://github.com/libigl/libigl/files/4467466/Ch …

Matcaps (material captures aka environment maps) in Viewer

---

include/igl/scaf.cpp

Fixes missing IGL_INLINE in scaf.cpp, which caused multiple include error when compiling in header-only mode.

Add missing IGL_INLINE in scaf.cpp

---

include/igl/opengl/glfw/Viewer.cpp

Fixes # .
igl::readOBJ might return a zero matrix for UV_V,UV_F

Fixed load_mesh for obj

---

include/igl/sort.cpp

Fixes the compilation error "incompatible operand types" when libigl is compiled with Eigen 3.3+.

Fix compilation error with Eigen 3.3+

---

cmake/LibiglFolders.cmake

I noticed that tutorial 719 was outside of the tutorials folder in the Visual Studio solution. After running a comparison against the other tutorials, it seems this line was missing from LibiglFolders.cmake. Regenerating the solution with this line added fixes the problem.

Add 719_ExplodedView to tutorials folder.

---

include/igl/file_dialog_open.cpp
include/igl/file_dialog_save.cpp

Should fix #1513. It seems the solution to the issue was correctly identified but no PR was made for it yet.
As far as I can tell there was a buffer (szBuffer) that was intended to be used instead of the dynamic allocation, but it was unused. I just made the structure use that buffer, which matches the size defined elsewhere.

Address memory heap corruption on Windows open dialog on long filenames

---

cmake/LibiglDownloadExternal.cmake
include/igl/opengl/glfw/imgui/ImGuiMenu.cpp
tutorial/106_ViewerMenu/main.cpp

- Clones latest release of Dear ImGui (`v1.76`)
- Resolved breaking change: Renames ImGui variables that were changed in `v1.51`
- Tested by building tutorial 106 and ensuring all the options in the ImGui Menu are still functional
- In `v1.76` Dear ImGui included `imgui.h` in some header files which are exposed directly to the application for invariance of ordering of include headers within usage of the library. (See https://github.com/ocornut/imgui/commit/00927105ba6b14f6d05a651b316428a8342fb4d3) This caused a breaking change for us as until now ImGui has not been exposed to libigl. Hence needed to make ImGui directory `PUBLIC` to libigl through `libigl-imgui` repo. However, this PR uses my fork of `libigl-imgui` which modifies the commit in current `libigl` master (`07ecd38`) to achieve …

ImGui Update to v1.76

---

include/igl/opengl/ViewerData.cpp

missing check for empty uv similar to line 747

Viewer crash after calling clear

---

include/igl/readPLY.cpp
include/igl/writePLY.cpp
tests/include/igl/writePLY.cpp

Fixed an error in writePLY when vertex coordinates are stored in single precision.

Fixed writing PLY file, when coordinates are stored as floats

---

include/igl/remove_duplicate_vertices.cpp
include/igl/remove_duplicate_vertices.h

Noticed in gptoolbox: https://github.com/alecjacobson/gptoolbox/issues/81
most of the time we use `epsilon=0` so this bug/confusion didn't matter.

Clarify, fix bug in epsilon parameter in remove_duplicate_vertices

---

include/igl/knn.cpp
include/igl/knn.h
include/igl/octree.cpp
tests/include/igl/knn.cpp

There are a  variety of minor improvements to KNN/octree to allow it to be run with floats and so KNN can be run between two different point clouds.
There is an API change is that "const KType&" was changed to int because it didn't need to be template deduced. The new knn call uses P and V point clouds as the points that need neighbors found and V for the points that will be neighbors. P==V reduces to the original implementation.
When |V| < k, the code now shortcuts to just writing out a list of indices, sorted by distances.

octree + knn imp

---

include/igl/opengl/MeshGL.cpp

Fixes https://github.com/libigl/libigl/issues/1605
I did not test whether text labels still work (assume they do since this just deleted an used variable).

Blindly fixing shader warning

---

include/igl/exact_geodesic.cpp

The print statement is always called, which affects debugging output of
calling code.
Fixes # .
Deletes a print statement in the exact geodesic method that only outputs whitespace.

Deletes print statement in the exact_geodesics method

---

cmake/LibiglDownloadExternal.cmake

As [Eigen is now on GitLab.com](http://eigen.tuxfamily.org/index.php?title=News:Eigen_is_now_on_GitLab.com) change path to Eigen's git repository in cmake.
The old github repo is only kept for convenience but does not receive further updates.
Using the repo on gitlab.com it's possible to change to the latest Eigen version 3.3.8 ([ChangeLog](http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.3.8) )
Whether updating to Eigen 3.3.8 is a good idea/worth it or not is another story.

Use new gitlab remote to clone Eigen.

---

include/igl/file_utils.cpp
include/igl/file_utils.h
include/igl/list_to_matrix.cpp
include/igl/list_to_matrix.h
include/igl/readPLY.cpp
include/igl/readSTL.cpp
include/igl/readSTL.h
include/igl/read_triangle_mesh.cpp
include/igl/string_utils.cpp
include/igl/string_utils.h

The following STLs from Thingi10K were not loading with the previous STL parser:
- 1482988.stl
- 1080516.stl
- 56117.stl
This PR updates our STL parser (copied over from [PyMesh](https://github.com/PyMesh/PyMesh)) to fix those issues. Previous code had a lot of `goto` in it so I got scared, and preferred to use another implementation.

 Update STL reader.

---

include/igl/readSTL.cpp

reset the position of the current character in the input
Fixes # .
Commit 1e905cba3d5e7d82487a6826d0d3fa7cd47de114 introduces bug in readSTL.
- when `is_stl_binary(...)` is called, the position of the current character for `std::istream input` is accidentally updated because of `input.read(...)`. So, I just add `input.seekg(...)` to reset the position.

Fix bug in readSTL

---

cmake/LibiglDownloadExternal.cmake

Fixes #1655.
Using latest commit of GLFW to include the fixes for CMake 3.19.0 on macOS: https://github.com/glfw/glfw/commit/3327050ca66ad34426a82c217c2d60ced61526b7

Bump GLFW due to an error on macOS with CMake 3.19.0

---

include/igl/writePLY.cpp
tests/include/igl/writePLY.cpp

Fixed a bug in writePLY, when face properties were doubled and edge properties were dropped

writePLY fix

---

include/igl/opengl/glfw/imgui/ImGuiHelpers.h

Fixes #1692. `ImGuiTextEditCallback` was renamed to `ImGuiInputTextCallback` [in 1.63 (august 2018)](https://github.com/ocornut/imgui/blob/94a432275b8ce29fa1dfb36439cfaf325e12a1ab/docs/CHANGELOG.txt#L1368), the old name was deprecated then, and [removed end of 2020](https://github.com/ocornut/imgui/blob/94a432275b8ce29fa1dfb36439cfaf325e12a1ab/docs/CHANGELOG.txt#L56).

ImGuiTextEditCallback was renamed/deprecated in Imgui 1.63 (2018)

---

include/igl/embree/EmbreeIntersector.cpp

Fixes https://github.com/libigl/libigl/issues/1708
adding "inline" keyword to class member func.
compilation passed.

fix: compilation error caused by missing "inline" keyword.

---

include/igl/default_num_threads.cpp
include/igl/default_num_threads.h
include/igl/parallel_for.h

Added environment variable IGL_PARALLEL_FOR_NUM_THREADS to control the number of threads used at runtime. The code is a static initializer and will only run once per process, therefore should have almost zero effect on performance. 
#1683

Control number of threads with IGL_PARALLEL_FOR_NUM_THREADS

---

include/igl/default_num_threads.cpp

Silence MSVC warning with std::getenv.

---

cmake/libigl.cmake

Only propagates /bigobj flag to C++ files, as the option is not
recognized by nvcc.
Fixes #1722

Fix Cuda compilation issue on Windows.

---

.github/workflows/continuous.yml
.github/workflows/nightly.yml

Github [recently removed](https://github.com/actions/virtual-environments/issues/2667) boost from its virtual images, so now we need to use conda on Windows to install it on the system.

Use boost via conda on Windows.

---

include/igl/embree/ambient_occlusion.cpp
include/igl/embree/ambient_occlusion.h

As discussed https://github.com/libigl/libigl/discussions/1750
Ambient occlusion should be able to have as input (like igl::per_vertex_normals) Eigen::MatrixBase matrices instead of Eigen::PlainObjectBase since the input is constant.
This would be useful to allow passing Eigen::Map objects to reduce memory duplication.
The change is as simple as replacing Eigen::PlainObjectBase with Eigen::MatrixBase for the input parameters

Replace Eigen::PlainObjectBase with Eigen::MatrixBase for input of ambient_occlusion

---

include/igl/opengl/ViewerData.cpp

`igl::opengl::ViewerData::set_labels` seems missing an update to the dirty flag. All changes made by `igl::opengl::ViewerData::set_labels` may not be drawn by the viewer.

Fix dirty flag for ViewerData::set_labels

---

include/igl/embree/EmbreeRenderer.cpp
include/igl/embree/EmbreeRenderer.h

Flag allows to render back side of faces, inside embree renderer. Similar to the ViewerData::double_sided

Added double_sided flag to embree renderer

---

include/igl/principal_curvature.cpp
tests/include/igl/principal_curvature.cpp
tutorial/203_CurvatureDirections/main.cpp

principle_curvature returns PD1, PV1 as minimal curvature direction and value, PD2, PV2 as maximum curvature direction and value.
The order is not the same as described in the docs(https://libigl.github.io/libigl-python-bindings/igl_docs/#principal_curvature) and the comments in the header file:
https://github.com/libigl/libigl/blob/36e8435a2f724e83e14f79d128102d06b514a4f4/include/igl/principal_curvature.h#L34-L38
Here's the code (using python bindings) and screenshot to demonstrate this bug:
```python
v, f = igl.cylinder(20, 20)
pd1, pd2, pv1, pv2 = igl.principal_curvature(v, f)
print(np.all(pv1<=pv2)) # printing true means pv2 is actually maximal curvature value
p = meshplot.plot(v, f, shading={"wireframe": False}, return_plot=True)
avg = igl.avg_edge_length(v, f) / 2
p.add_lines(v + …
```

Fix the order of principal curvature

---

cmake/LibiglDownloadExternal.cmake
include/igl/triangle/triangulate.cpp

Switch triangle version to [one where it's possible to customize the function `triexit`](https://github.com/libigl/triangle/commit/9cceb2f0c9d364ec229fd9182b4f45e3c5bed63a) which is called when triangle fails.
Meanwhile, in libigl provide this custom implementation to throw a `std::runtime_exception`.
(Note, this change is unrelated to switching to https://github.com/qnzhou/trianglelite . That may be a good idea in the future but doesn't immediately solve the problem of triangle calling exit)

Instead of calling `exit(1)`, teach triangle to throw exception

---

cmake/LibiglDownloadExternal.cmake

The latest libigl triangle now has a conservative bail out for an [infinite loop bug](https://github.com/qnzhou/trianglelite) in the original triangle.

Bumps the triangle version

---

cmake/LibiglDownloadExternal.cmake

tetgen commit hash was pointing to the wrong repo. Meanwhile, tetgen has released a new version, now mirrored in https://github.com/libigl/tetgen

bump tetgen commit hash

---

include/igl/lscm.cpp
include/igl/lscm.h
tests/include/igl/lscm.cpp

I'm pretty sure this fix is correct -- the area term should be subtracted, not added.
To confirm the correctness, I wrote the following code
```c++
#include "grad.h"
#include "doublearea.h"
#include "per_face_normals.h"
double compute_lscm_energy(
const Eigen::MatrixXd& V,
const Eigen::MatrixXi& F,
const Eigen::VectorXd& W_flat)
{
const int nV = V.rows();
const int nF = F.rows();
// Compute gradient
Eigen::SparseMatrix<double> G;
igl::grad(V, F, G);
Eigen::VectorXd nablaU_flat = G * W_flat.head(nV);
Eigen::VectorXd nablaV_flat = G * W_flat.tail(nV);
Eigen::MatrixXd nablaU(nF, 3);
Eigen::MatrixXd nablaV(nF, 3);
nablaU << nablaU_flat.segment(0, nF), nablaU_flat.segment(nF, nF), nablaU_flat.segment(2 * nF, nF);
nablaV << nablaV_flat.segment(0, nF), nablaV_flat.segment(nF, nF), …
```

lscm: fix sign for the area term

---

include/igl/file_utils.cpp

Fixes # .
add ```fclose(File* fp).```
from in ```file_utils.cpp```
```
if (!ferror(fp)) {
fseek(fp, 0, SEEK_END);
size_t sizeBytes = ftell(fp);
fseek(fp, 0, SEEK_SET);
fileBufferBytes.resize(sizeBytes);
if (fread((char*)fileBufferBytes.data(), 1, sizeBytes, fp) == sizeBytes) 
return;
}
```
to
```
if (!ferror(fp)) {
fseek(fp, 0, SEEK_END);
size_t sizeBytes = ftell(fp);
fseek(fp, 0, SEEK_SET);
fileBufferBytes.resize(sizeBytes);
if (fread((char*)fileBufferBytes.data(), 1, sizeBytes, fp) == sizeBytes) {
fclose(fp);
return;
}
}
```

fix bug in read_file_binary(FILE *fp, std::vector<uint8_t> &fileBufferBytes)

---

include/igl/serialize.h

Something very minor.. but I was searching through the source where the `is not serializable: derive from igl::Serializable or spezialize the template function` message came from by searching for 'specialize'.

Typo in stderr message in serialize

---

include/igl/arap.cpp
include/igl/arap.h

This Pull Request implements changes discussed here: https://github.com/libigl/libigl/discussions/1920
By changing the interface to accept Eigen::MatrixBase instead of Eigen::PlainObjectBase, it becomes possible to pass data to libigl through Eigen::Map-ped data. It allows the user more flexibility in representing mesh data in their code while not requiring unnecessary copies to Eigen matrices, when a Map can be used.
- [x ] This is a minor change.

Modified arap interface to accept Eigen::Map

---

cmake/recipes/external/imgui.cmake
cmake/recipes/external/imguizmo.cmake
include/igl/opengl/glfw/imgui/ImGuiHelpers.h
include/igl/opengl/glfw/imgui/ImGuiMenu.cpp
include/igl/opengl/glfw/imgui/ImGuiTraits.h
include/igl/opengl/glfw/imgui/ImGuizmoPlugin.cpp
include/igl/opengl/glfw/imgui/ImGuizmoPlugin.h
include/igl/opengl/glfw/imgui/SelectionPlugin.cpp
include/igl/opengl/glfw/imgui/SelectionPlugin.h
include/igl/serialize.h
tutorial/106_ViewerMenu/main.cpp
tutorial/109_ImGuizmo/main.cpp
tutorial/409_Kelvinlets/main.cpp

Updates CMake code to use the repo imgui and imguizmo as the only include path. This avoids the hack of copying headers around and makes libigl code compatible with other codebase including imgui in their own projects.
Client code using ImGuiMenu.h should not need to include `imgui.h` (since it's already included by `ImGuiMenu.h`), but if they do, the following modifications would be required:
- `#include <imgui/imgui.h>` --> `#include <imgui.h>`
- `#include <imgui/imgui_internal.h>` --> `#include <imgui_internal.h>`
- `#include <imgui_impl_glfw.h>` --> `#include <backends/imgui_impl_glfw.h>`
- `#include <imgui_impl_opengl3.h>` --> `#include <backends/imgui_impl_opengl3.h>`

Update ImGui to v1.85 + use default include folders.

---

cmake/recipes/external/embree.cmake

Fixes embree compilation issues on M1 macs (related to #1686). Tutorials and tests run correctly with version 3.13.3.

Bump embree to 3.13.3

---

cmake/recipes/external/catch2.cmake

The previously used Catch2 version fails to build with glibc >= 2.34.
As MINSIGSTKSZ can no longer be assumed to be constant:
* https://sourceware.org/git/?p=glibc.git;a=commit;h=6c57d320484988e87e446e2e60ce42816bf51d53
* https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html
It's fixed in Catch2 since 2.13.5: https://github.com/catchorg/Catch2/releases/tag/v2.13.5
The upcoming Ubuntu LTS (22.04) will ship with an incompatible glibc version.

Update Catch2 to latest version (v2.13.8)

---

include/igl/doublearea.cpp

Fixes # .
The type of doublearea_tri is inconsistent with input parameter dblA

consistent type deduction

---

include/igl/marching_cubes.cpp

marching_cubes used mutable static variable causing race condition in multi-threaded code. Removed static keyword to make it work properly.

Fixed thread unsafe code in marching_cubes.cpp

---

include/igl/opengl/ViewerCore.cpp
include/igl/opengl/ViewerData.cpp
include/igl/opengl/ViewerData.h

Fixes # .
using label color for text and added scaling factor for labels to viewer data

Fixing label stuff

---

cmake/recipes/external/cgal.cmake

CGAL's git repository is ginormous (> 1GB). cmake's FetchContent has the `GIT_SHALLOW` but this still results in a huge download. If we're using a release of cgal then there's not much advantage to use git anyway. Hence, switch to url fetch → significantly smaller download ~35MB.

Use URL to download CGAL source rather than git

---

include/igl/opengl/glfw/imgui/ImGuiMenu.cpp

The `ImGuiMenu` class currently constraints the width to a hardcoded value, and also enables auto-resizing. Both of these settings overlap, in that they both prevent the user from resizing the ImGui menu, but the width constraint effectively overrides the auto-resizing feature, which sets the width at a potentially undesirable value (e.g., wide content can be truncated). Removing the width constraint and just letting ImGui resize the menu automatically seems to be a good approach. I've only tested this on some code in a private repo that I don't want to share publicly, but I am happy to write up a simple example demonstrating the change, or discuss an alternative approach (e.g., perhaps a user might want to set a maximum width constraint or manually fix the width on their end).

Remove hardcoded ImGui menu width constraint

---

tests/include/igl/lscm.cpp

Sorry, I made this wrong assertion which causes the debug build to fail.

test/lscm: fix wrong assertion

---

include/igl/average_onto_faces.h
include/igl/signed_distance.h

Relate to this question: https://github.com/libigl/libigl/discussions/2006
Also contains another comment correction for `signed_distance.h` header file.

mod: correct comments in header files.

---

include/igl/moments.cpp
include/igl/moments.h
tests/include/igl/moments.cpp

Computer moment of inertia and other mass moments given triangle mesh.
`igl::centroid` should probably just call this function and ignore outputs.
We could also make a `igl::volume(V,F,scalar_volume)` overload that computes the volume of triangle mesh.
Fixes #1507 in a way. `igl::centroid` was always an awkward name for getting a solid's volume.

moments of mass

---

cmake/recipes/external/cgal.cmake
cmake/recipes/external/gmp.cmake
cmake/recipes/external/mpfr.cmake

Fixes #2014
(also circumvents pesky cmake warning from cgal)

Make CONFIGURE_HANDLED_BY_BUILD optional dependent on cmake version

---

cmake/recipes/external/cgal.cmake
cmake/recipes/external/gmp.cmake

Fixes #2029
gmpxx is part of gmp and we're building it via cmake. Previously we weren't telling cgal where to find it and on some machines (mine at least) it was finding it at /usr/local/include. This caused /usr/local/include to be added to include paths which caused #2029 to happen (cgal was also found there and confused).
This should tell cgal where to find gmpxx and subsequently _not_ add /usr/local/include.

point GMPXX_INCLUDE_DIR to locally built gmp

---

include/igl/exact_geodesic.cpp
tests/include/igl/exact_geodesic.cpp

This PR allows 2D input to exact_geodesic (trivially by appending 0s during the copy that's already there). I also noticed a bug in how the targets were setup (overwriting each other), which I fixed along the way. Added a test case and removed a weird template.
> `igl::exact_geodesic` belongs to the set of "this is a libigl wrapper of an external piece of code". I'm not sure how much has been done on the original code for this wrapper and this PR doesn't change that.

exact_geodesic: fix bugs, clean up asserts, allow 2D

---

include/igl/dual_contouring.cpp

The previous version of the code would call new_vertex() outside of the mutex right below it, which would in turn trigger a call to resize a bunch of std::vector<>s. The patch addresses the issue by moving the vertex such that the initialization of ev is contained within the mutex.
Fixes #2044.
Tested by meshing a handful of signed distance fields created using Chris Batty's SDF generator.

Fixes a race condition in the dual contouring code.

---

include/igl/copyleft/tetgen/tetgenio_to_tetmesh.cpp

I'm not sure why this `if` was here in the first place. This function doesn't extract markers. (seems either qnzhou or daneielpanozzo wrote the original line).  Before this fix, if the face list existed but markers did not, then it would crash. Now, it ignores the possibility of markers and extracts existing faces.
(Properly extracting markers is left for a future PR).

Tetgen: fix bug when faces don't have markers

---

include/igl/lscm.cpp

The fix in #1853 causes the solution UVs to be flipped, so this is a simple fix to that.
See attached a parameterization of an example surface. Apologies in advance for no reproducible example code in C -- I've been working with the python bindings and whipped this up on short notice.

lscm: fix order of UV after area term sign fix

---

include/igl/writePLY.cpp

Signed-off-by: BruegelN <BruegelN@crashing.systems>
~~Fixes # .~~
This is likely a typo as comparing the size of the edge data and faces doesn't make much sense.
When compiling libigl in debug mode this test failed with:
```
165/204 Testing: writePLY: bunny.ply
165/204 Test: writePLY: bunny.ply
Command: "~/libigl/Debug/tests/test_igl_core" "writePLY: bunny.ply"
Directory: ~/libigl/Debug
"writePLY: bunny.ply" start time: Jan 03 19:45 CET
Output:
----------------------------------------------------------
test_igl_core:~/libigl/include/igl/writePLY.cpp:144: bool igl::writePLY(std::ostream&, const Eigen::MatrixBase<Derived>&, const Eigen::MatrixBase<U>&, const Eigen::MatrixBase<DerivedE>&, const Eigen::MatrixBase<DerivedN>&, const Eigen::MatrixBase<DerivedUV>&, const …
```

Fix typo in test that caused test failure in Debug mode

---

.github/workflows/continuous.yml

CI is failing because I think `brew update` is sending a failing exit code. https://github.com/libigl/libigl/actions/runs/3832188849/jobs/6522212468
It seems everything is continuing to install fine but it doesn't like that it can't create python links (which I don't believe we're using).
This fix ([suggested here](https://github.com/actions/setup-python/issues/577)) just forces the update to return true. It seems that many others just run `brew install ccache` without `brew update`. Not sure if we still need `brew update` or if that was from when we used brew to get gmp and mpfr.
Another option would be to install ccache in some more reproducible way, but I don't have the bandwidth to figure that out at the moment.

don't crash on brew update

---

cmake/recipes/external/imgui.cmake

Fixes # .
fix imgui costs much time to clone by adding "GIT_SHALLOW TRUE"

chore(cmake): use GIT_SHALLOW for imgui

---

include/igl/boundary_facets.cpp

Fixes # .
This is an optimization of the boundary_facets method. The ```switch(simplex_size)``` has been moved outside the loop avoiding to test the condition again and again for each tet/triangle.
- [ x] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [x ] This is a minor change.

boundary_facets_optimization

---

include/igl/opengl/glfw/Viewer.cpp

Previously the Viewer was throttling only when animating. This helps (a bit) when rendering is slow and dragging around with the mouse.

throttle tight loop over glfwWaitEvents with sleep

---

include/igl/opengl/MeshGL.cpp
include/igl/opengl/ViewerCore.cpp
include/igl/opengl/ViewerCore.h
include/igl/opengl/glfw/Viewer.cpp
include/igl/opengl/read_pixels.cpp
include/igl/opengl/read_pixels.h
tutorial/113_Shadows/main.cpp
tutorial/CMakeLists.txt

Shadows!
**Before:**
**After:**
Pretty straightforward shadow mapping implementation for directional lights. I'm guessing this could be optimized, but I'd like to have something in there for visualization of things where close contact is important, like, contact simulations.
I left a few notes about the funny coordinate system for our current positional lights. I didn't change that yet, but I think if we upgrade this to handle point lights then it'd worth reconsidering the coordinate system lights live in.
For now lights are turned off by default and can be turned on with `'S','s'`. That'll also switch to directional lights.
I kinda like the floor in those renderings, but for now it's just ad hoc for the new tutorial entry. (actual tutorial entry to follow in that repo). Try it out in …

Shadow Mapping in igl::opengl::glfw::Viewer

---

include/igl/readMESH.cpp

Fixes #2141 
The readMESH function is caught in an endless loop (while ignoring comments/empty lines). It fails to get a new line, and continues to check the previous line.
The mesh was ceeated with tetgen (libigl wrapper) and saved using writeMESH.

BUG: readMESH stuck in endless loop

---

include/igl/opengl/glfw/Viewer.cpp

Fixes # .
From what I know of OpenGL, both width and height must be handled to resize window to frame.
Not 100% sure!...I PR that as a proposal: I let you decide if it's a good move
`make all test` runs OK at my side (debian)

glfw viewer - high dpi: handling both width and height.

---

include/igl/copyleft/comiso/nrosy.cpp

Omit last (show_timings) argument for ConstraintedSolver::solve call.
This was optional before, and has been removed in CoMISo
[174ef38344e09a9547f8a684bf6520cdc8fbe3ba](https://gitlab.vci.rwth-aachen.de:9000/CoMISo/CoMISo/-/commit/174ef38344e09a9547f8a684bf6520cdc8fbe3ba)

CoMISo-MRosy solver: compatibility with newer CoMISo:

---

.github/workflows/continuous.yml

The hope is that now that the build is more split up after https://github.com/libigl/libigl/pull/2165 we can restore https://github.com/libigl/libigl/pull/2161 . I think there's a theory that the "out of heap space" errors are when two threads are using a ton of memory at the same time. If that's the case, the simple split of tests and tutorial won't necessarily change. I think I roughly know which units take tons of memory (in the header only it's usually the CGAL module ones). So I guess a further idea would be to see if we can force CMAKE to be serial for just those.
Maybe an even better option would be to see if we can use https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

try to use j2 on windows CI

---

include/igl/read_file_binary.h

Fixes # .
Added missing headers <cstdint> in order to fix build with GCC 13.
ref: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes

Add missing <cstdint> header for gcc 13

---

cmake/recipes/external/gmp.cmake

GMP .zip is [failling to download repeatedly during CI](https://github.com/libigl/libigl/actions/runs/5365140085/jobs/9741350204). When I try locally the link works fine, so I guess it's getting unlucky with the gmp server?
This PR switches to [an up-to-date mirror I found](https://github.com/alisw/GMP).

switch to gmp mirror

---

cmake/igl/libigl-config.cmake.in

Fixes #2186 (or a part of it)
Fix the packaging of igl so that the core library is correctly found. Tested on WSL-Ubuntu-20.04 with GCC 9.4.0. 
```cmake
find_package(libigl CONFIG REQUIRED)
target_link_libraries(main PUBLIC igl::igl_core)
```

Fix CMake package installation for igl_core

---

include/igl/copyleft/cgal/RemeshSelfIntersectionsParam.h
include/igl/copyleft/cgal/SelfIntersectMesh.h
include/igl/copyleft/cgal/intersect_other.cpp

Fixes #270
CGAL weirdly uses a pretty bad default for the somewhat mysterious `cutoff` parameter in box_intersections_d and box_self_intersections_d
I tired 1,10,100,1000,10000,100000 and √n for all the tutorial data models (not a particularly good test set) and 1000 was the clear winner.
So, this now uses that as the default and exposes the parameter for users to tweak if needed.
The speedups are modest (like 1.1-1.2x).

Expose cutoff parameter for CGAL intersections; better default

---

include/igl/point_mesh_squared_distance.cpp
include/igl/readPLY.cpp
include/igl/readPLY.h

Fixes #436
This uses class template specialization to avoid ever calling AABB with conflicting template params (e.g., MatrixX3D and DIM=2). The old code was all dynamic so it lead to conflicting compilation paths.
I claim this is a reasonable C++11 solution. If we were using C++17 then we could use `if constexpr` which would be significantly less code and more readable.
Unless I notice something broken with this, I'll also fix the nasty dynamic situation in `signed_distance` similarly. And then we can add [to AABB] a 
```cpp
static_assert(DerivedV::ColsAtCompileTime == DIM || DerivedV::ColsAtCompileTime == Eigen::Dynamic,"V's #columns must either match DIM or be Dynamic.");
```
So that bogus compilation paths get caught.

Avoid conflicting template parameters in AABB

---

include/igl/opengl/MeshGL.h

Added #include <cstdint> for fixing build failure for [mingw-w64 "w64devkit"](https://www.mingw-w64.org/downloads/#w64devkit)
The reason to use w64devkit on Windows is the toolchain includes pthreads, C++11 threads, and OpenMP.
Fixes the following types of errors in libigl example project:
`libigl-example-project/build/_deps/libigl-src/include/igl/opengl/MeshGL.h:91:5: error: 'uint32_t' does not name a type
91 |     uint32_t dirty_flag;` and
`libigl-example-project/build/_deps/libigl-src/include/igl/opengl/MeshGL.cpp:56:3: error: 'dirty' was not declared in this scope
56 |   dirty = MeshGL::DIRTY_ALL;`
After the fix, the project builds successfully. However, the following line must be added to [libigl-example-project](https://github.com/libigl/libigl-example-project) `CMakeLists.txt` to …

Update MeshGL.h for successful build in Mingw Windows

---

cmake/recipes/external/boost.cmake

Boost's jfrog artifactory servers went bad somehow over the new year. It seems that if we ever bump boost to a modern version we should just use their github releases. I also don't really understand what role this extra `boost-cmake` repo is playing for us now. Is it needed? In any case, for now I forked it and changed the 1.71.0 url to something that doesn't crash.

use our boost-cmake which uses slow, non-jfrog url

---

include/igl/cut_mesh.cpp
include/igl/cut_mesh.h
tests/include/igl/cut_mesh.cpp

Fixes #2314 
Previously it seems that `cut_mesh` would fail to cut or even crash if only one incident face marked an edge to cut. 
A less ambiguous interface might be to use the edge-flaps arrays like collapse_edge. Leaving this to a future date / never.

fix bug in cut_mesh; improve documentation; add test

---

include/igl/copyleft/tetgen/mesh_to_tetgenio.cpp
include/igl/copyleft/tetgen/tetrahedralize.h
tests/include/igl/copyleft/tetgen/tetrahedralize.cpp

Fixes #2337.
This change adds support for mixed polygons, e.g. triangles and segments.

enable mixed polygons using convention that negative indices are ignored

---

include/igl/split_nonmanifold.cpp
include/igl/unique_edge_map.h
tests/include/igl/split_nonmanifold.cpp

The previous method (and the old one in gptoolbox) was cool cause it wouldn't just create boundaries at the non-manifold edge chains. It would identify big manifold components across non-manifold edges. Unfortunately, it was just getting lucky. It would find those if they were _in order_ in the list of faces, and fail to correctly split the mesh oetherwise. (Some of the new tests will fail the old code).
At one point I set out to implement "Cutting and Stitching: Converting Sets of Polygons to Manifold Surfaces" [Guéziec et al. 2001] but its details are a bit confusing and it's not quite written with proofs so I got nervous I'd make an elaborate implementation and still have failure cases.
Instead, I implemented the "obvious" thing. Split all the edges, then try to stitch them back. Only …

Fix split_nonmanifold

---

include/igl/WindingNumberTree.h

This is a follow up fix of #2254. After #2254 gcc-12.3 reports the error "template-id not allowed for destructor".

Fix compile error on gcc-12.3

---

include/igl/active_set.cpp
include/igl/bbw.cpp
include/igl/copyleft/cgal/SelfIntersectMesh.h
include/igl/copyleft/cgal/closest_facet.cpp
include/igl/copyleft/cgal/order_facets_around_edge.cpp
include/igl/copyleft/cgal/order_facets_around_edges.cpp
include/igl/copyleft/cgal/projected_delaunay.cpp
include/igl/copyleft/cgal/propagate_winding_numbers.cpp
include/igl/copyleft/tetgen/mesh_with_skeleton.cpp
include/igl/eigs.cpp
include/igl/embree/EmbreeDevice.h
include/igl/embree/bone_heat.cpp
include/igl/min_quad_with_fixed.impl.h
include/igl/mvc.cpp
include/igl/planarize_quad_mesh.cpp
include/igl/principal_curvature.cpp
include/igl/rotation_matrix_from_directions.cpp
include/igl/slim.cpp
include/igl/squared_edge_lengths.cpp

We're not very consistent about when we fire assertions, print to stderr or throw runtime errors.
This cleans up a bunch of `cerr<<` error messages that were either already caught by `assert` in debug mode, printing messages before `return false`. Or for functions that are commonly needing debugging hides them behind appropriate `ifdef`s. There's still a bunch of error message printing in functions dealing with file IO or in modules I'm not touching (e.g., comiso).

remove or hide cerr<< behind ifdef

---

include/igl/readOBJ.cpp

Fixing shadowed variable declaration (that may lead to a compiler error if `-Werror=shadow`)
Variable `f` is previously defined as `std::string`

Fixing readOBJ  shadowed variable declaration

---

include/igl/predicates/find_intersections.cpp

This non-manifold input was generating false positives in find_self_intersections. It was because shared_edge was assuming consistent orientations.  No need for this assumption. 
[two_cubes.obj.zip](https://github.com/user-attachments/files/15808916/two_cubes.obj.zip)

allow shared edge to be conflictingly oriented

---

include/igl/AABB.cpp
include/igl/AABB.h

I'm trying to make my code run fine through MemorySanitizer. I'm running into a case where the `look_left/right` routines might call `set_min()` with an uninitialized `i_left/i_right` index. This is fine because `set_min()` is called with `sqr_d_candidate == sqr_d`, so the uninitialized index is never assigned. But changing the arg to a `const &` avoids reading the value from memory and thus makes MemorySanitizer happy.

Change arg to const & to avoid MSan issue.

---

include/igl/AABB.h

This fixes a build error on g++-14 RISC-V toolchain. Just a missing include.

Add missing include <cassert> in AABB.h

---

include/igl/voxel_grid.h

Clarify the documentation of `voxel_grid.h`. The `offset` parameter does something different (and more useful) than the current documentation suggests.

Update voxel_grid.h documentation

---

include/igl/opengl/glfw/Viewer.cpp

In `Viewer.cpp` the way the `highdpi` value was calculated could lead to it being set to 0 or `inf` for certain types of window managers. (Tiling window managers). This was caused by the WM trying to resize the window to a width and height of 0 by 0, or by having the logical width/height of the window be smaller than the pyhsical one. This would later cause a glfw call to be made with `inf` as an argument, which causes an assertion to be raised in debug mode.
Fixes (no issue exists).
1. I added a check in `Viewer::launch_init(...)` method to check that we don't divide by 0.
2. I fixed a problem where two `int`s would be used for a division, which would cause the value to be 0 instead of $\in [0,1]$.

Fix bug for highdpi calculation in Viewer.cpp

---

include/igl/AABB.cpp
include/igl/AABB.h
include/igl/HalfEdgeIterator.cpp
include/igl/HalfEdgeIterator.h
include/igl/circulation.cpp
include/igl/copyleft/cgal/trim_with_solid.cpp
include/igl/flip_edge.cpp
include/igl/grad_intrinsic.cpp
include/igl/intrinsic_delaunay_triangulation.cpp
include/igl/kkt_inverse.h
include/igl/remesh_along_isoline.cpp
tests/include/igl/triangle_triangle_intersect.cpp

To avoid compiler warnings of the style:
```
include/igl/AABB.cpp:549:3: warning: multi-line comment [-Wcomment]
549 |   //            /  \
```
I've replaced comments using forward/backward slashes with unicode box-drawing characters. This avoids ending a comment with a trailing backslash, which can trigger some annoying compiler warnings.

Use box-drawing characters in comments.

---

tutorial/303_LaplaceEquation/main.cpp

Fixes Laplace equation tutorial code for the linear solver approach.
Need to comment out the alternate method for the quadratic energy minimization approach (`igl::min_quad_*`) to expose bug.
Corresponds to [Chapter 3: Matrices And Linear Algebra > Laplace Equation](https://libigl.github.io/tutorial/#laplace-equation).
Bugged camel head:
Fixed camel head:

laplace equation tutorial - fixed bug with slice/lazy eval

---

include/igl/dijkstra.cpp

Using an index type other than `int` (e.g. `Eigen::Index`) was leading to build errors.

dijkstra: Fix inconsistent typing

---

cmake/igl/igl_add_tutorial.cmake

For some reason, Apple binaries need to be signed, but sometimes are already signed.  This triggers an error in codesign unless the force (-f) flag is passed.
Fixes #2493 .

Force codesign to sign binaries, even if they are already signed
